name: Bump version
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get Token
        id: get_workflow_token
        uses: actions/create-github-app-token@v1
        with:
          app_id: ${{ secrets.APPLICATION_ID }}
          private_key: ${{ secrets.APPLICATION_SECRET }}
      - uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: "v1.0.0"
          tag_exists_error: false
          message: "Latest release"
          github_token: ${{ steps.get_workflow_token.outputs.token }}
